version: '3.8'

services:
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: mysqld --sql_mode=""
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./_bdd:/docker-entrypoint-initdb.d

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - "10001:80"
      environment:
        - PMA_HOST=mysqldb
        - PMA_PORT=3306

